export const SELECT_CHANNEL = 'SELECT_CHANNEL'

export const DESELECT_CHANNEL = 'DESELECT_CHANNEL'

export const REQUEST_NEWS = 'REQUEST_NEWS'

export const RECEIVE_NEWS = 'RECEIVE_NEWS'

export const API_FAIL = 'API_FAIL'
